<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Hardlopen" Id="{595a4fa8-c535-4084-8182-3622c9324e38}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Hardlopen
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Hardlopen">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>